<a href="https://colab.research.google.com/github/SHRIDHARKN/pytorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import numpy as np

In [5]:
np.random.rand(3,4)

array([[0.51179604, 0.85008153, 0.4401542 , 0.005948  ],
       [0.09029129, 0.46975211, 0.91699994, 0.21468247],
       [0.68883793, 0.03219568, 0.65903709, 0.57372836]])

In [6]:
torch.rand(3,4)

tensor([[0.8723, 0.4072, 0.7749, 0.7489],
        [0.1531, 0.1149, 0.1263, 0.1449],
        [0.4850, 0.9299, 0.2040, 0.2670]])

In [12]:
torch.rand(5,2,3)

tensor([[[0.6718, 0.8967, 0.9837],
         [0.3922, 0.8380, 0.4600]],

        [[0.0895, 0.6410, 0.9279],
         [0.0506, 0.5461, 0.5423]],

        [[0.7702, 0.9938, 0.0792],
         [0.0778, 0.9129, 0.3407]],

        [[0.4541, 0.2830, 0.1017],
         [0.0921, 0.9216, 0.5995]],

        [[0.1207, 0.0225, 0.8866],
         [0.3632, 0.2390, 0.9239]]])

In [13]:
torch.tensor(np.random.rand(2,3))

tensor([[0.2822, 0.4856, 0.2884],
        [0.4365, 0.8431, 0.4092]], dtype=torch.float64)

In [14]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
torch.arange(10).reshape(5,2)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [19]:
torch.arange(10).reshape(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
torch.tensor([2,4,6])+torch.tensor([6,2,4])

tensor([ 8,  6, 10])

In [21]:
torch.add(torch.tensor([2,4,6]),torch.tensor([6,2,4]))

tensor([ 8,  6, 10])

In [22]:
torch.sub(torch.tensor([2,4,6]),torch.tensor([6,2,4]))

tensor([-4,  2,  2])

In [23]:
torch.mul(torch.tensor([2,4,6]),torch.tensor([6,2,4]))

tensor([12,  8, 24])

In [24]:
torch.div(torch.tensor([2,4,6]),torch.tensor([6,2,4]))

tensor([0.3333, 2.0000, 1.5000])

In [26]:
torch.remainder(torch.tensor([2,4,6]),torch.tensor([6,2,4]))

tensor([2, 0, 2])

In [27]:
torch.pow(torch.tensor([2,4,6]),torch.tensor([6,2,4]))

tensor([  64,   16, 1296])

In [29]:
torch.tensor([2,4,6]).add_(torch.tensor([2,4,6]))

tensor([ 4,  8, 12])

In [31]:
# basic nn
import torch.nn as nn
import torch.nn.functional as F

In [37]:
class model(nn.Module):

    # inp - 4 feats
    # hidden
    # 3 classes predict

    def __init__(self,n_feats=4,h1=8,h2=9,out_feats=3):
        super().__init__()
        self.fc1 = nn.Linear(n_feats,h1)
        self.fc2 = nn.Linear(h1,h2)
        self.out = nn.Linear(h2,out_feats)

    def forward(self,x):
        x = F.relu( self.fc1(x))
        x = F.relu(self.fc2(x))
        x =  self.out(x)

        return x

In [35]:
torch.manual_seed(42)

In [38]:
ann = model()